In [ ]:
# from urllib.request import urlopen
# import ssl
# import json

# ctx = ssl.create_default_context()
# ctx.check_hostname = False
# ctx.verify_mode = ssl.CERT_NONE

# dataTrain1 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_001.json", context=ctx).read().decode()
# dataTrain2 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_002.json", context=ctx).read().decode()
# dataTrain3 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_003.json", context=ctx).read().decode()
# dataTrain4 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_004.json", context=ctx).read().decode()
# dataTrain5 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_005.json", context=ctx).read().decode()
# dataTrain6 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_006.json", context=ctx).read().decode()
# dataTrain7 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_007.json", context=ctx).read().decode()
# dataTrain8 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_008.json", context=ctx).read().decode()
# dataTrain9 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_009.json", context=ctx).read().decode()
# dataTrain10 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_010.json", context=ctx).read().decode()
# dataTrain11 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_011.json", context=ctx).read().decode()
# dataTrain12 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_012.json", context=ctx).read().decode()
# dataTrain13 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_013.json", context=ctx).read().decode()
# dataTrain14 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_014.json", context=ctx).read().decode()
# dataTrain15 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_015.json", context=ctx).read().decode()
# dataTrain16 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_016.json", context=ctx).read().decode()
# dataTrain17 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/train/dialogues_017.json", context=ctx).read().decode()

# dataTest1 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/test/dialogues_001.json", context=ctx).read().decode()
# dataTest2 = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/data/MultiWOZ_2.2/test/dialogues_002.json", context=ctx).read().decode()

# myJsonTrain1 = json.loads(dataTrain1)
# myJsonTrain2 = json.loads(dataTrain2)
# myJsonTrain3 = json.loads(dataTrain3)
# myJsonTrain4 = json.loads(dataTrain4)
# myJsonTrain5 = json.loads(dataTrain5)
# myJsonTrain6 = json.loads(dataTrain6)
# myJsonTrain7 = json.loads(dataTrain7)
# myJsonTrain8 = json.loads(dataTrain8)
# myJsonTrain9 = json.loads(dataTrain9)
# myJsonTrain10 = json.loads(dataTrain10)
# myJsonTrain11 = json.loads(dataTrain11)
# myJsonTrain12 = json.loads(dataTrain12)
# myJsonTrain13 = json.loads(dataTrain13)
# myJsonTrain14 = json.loads(dataTrain14)
# myJsonTrain15 = json.loads(dataTrain15)
# myJsonTrain16 = json.loads(dataTrain16)
# myJsonTrain17 = json.loads(dataTrain17)

# myJsonTest1 = json.loads(dataTest1)
# myJsonTest2 = json.loads(dataTest2)

# print (json.dumps(myJsonTrain1[0], indent=1)[0:100])
# print (json.dumps(myJsonTest1[0], indent=1)[0:100])



{
 "dialogue_id": "PMUL4398.json",
 "services": [
  "restaurant",
  "hotel"
 ],
 "turns": [
  {
   "
{
 "dialogue_id": "MUL0484.json",
 "services": [
  "attraction",
  "train"
 ],
 "turns": [
  {
   "f


In [ ]:
#http://alexminnaar.com/2019/08/22/ner-rnns-tensorflow.html
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

import numpy as np
import os
import time

print(tf.__version__)

2.5.0


In [ ]:
# import re

# from nltk.util import ngrams

# timepat = re.compile("\d{1,2}[:]\d{1,2}")
# pricepat = re.compile("\d{1,3}[.]\d{1,2}")

# fin = urlopen("https://raw.githubusercontent.com/budzianowski/multiwoz/master/utils/mapping.pair", context=ctx)
# replacements = []
# for line in fin.readlines():
#     line = line.decode().replace('\n', '')
#     tok_from, tok_to = line.replace('\n', '').split('\t')
#     replacements.append((' ' + tok_from + ' ', ' ' + tok_to + ' '))


# def insertSpace(token, text):
#     sidx = 0
#     while True:
#         sidx = text.find(token, sidx)
#         if sidx == -1:
#             break
#         if sidx + 1 < len(text) and re.match('[0-9]', text[sidx - 1]) and \
#                 re.match('[0-9]', text[sidx + 1]):
#             sidx += 1
#             continue
#         if text[sidx - 1] != ' ':
#             text = text[:sidx] + ' ' + text[sidx:]
#             sidx += 1
#         if sidx + len(token) < len(text) and text[sidx + len(token)] != ' ':
#             text = text[:sidx + 1] + ' ' + text[sidx + 1:]
#         sidx += 1
#     return text


# def normalize(text):
#     # lower case every word
#     text = text.lower()

#     # replace white spaces in front and end
#     text = re.sub(r'^\s*|\s*$', '', text)

#     # hotel domain pfb30
#     text = re.sub(r"b&b", "bed and breakfast", text)
#     text = re.sub(r"b and b", "bed and breakfast", text)

#     # normalize phone number
#     ms = re.findall('\(?(\d{3})\)?[-.\s]?(\d{3})[-.\s]?(\d{4,5})', text)
#     if ms:
#         sidx = 0
#         for m in ms:
#             sidx = text.find(m[0], sidx)
#             if text[sidx - 1] == '(':
#                 sidx -= 1
#             eidx = text.find(m[-1], sidx) + len(m[-1])
#             text = text.replace(text[sidx:eidx], ''.join(m))

#     # normalize postcode
#     ms = re.findall('([a-z]{1}[\. ]?[a-z]{1}[\. ]?\d{1,2}[, ]+\d{1}[\. ]?[a-z]{1}[\. ]?[a-z]{1}|[a-z]{2}\d{2}[a-z]{2})',
#                     text)
#     if ms:
#         sidx = 0
#         for m in ms:
#             sidx = text.find(m, sidx)
#             eidx = sidx + len(m)
#             text = text[:sidx] + re.sub('[,\. ]', '', m) + text[eidx:]

#     # weird unicode bug
#     text = re.sub(u"(\u2018|\u2019)", "'", text)

#     # replace time and and price
#     times = re.findall(timepat, text)
#     prices = re.findall(pricepat, text)
#     text = re.sub(timepat, ' [value_time] ', text)
#     text = re.sub(pricepat, ' [value_price] ', text)
#     #text = re.sub(pricepat2, '[value_price]', text)

#     # replace st.
#     text = text.replace(';', ',')
#     text = re.sub('$\/', '', text)
#     text = text.replace('/', ' and ')

#     # replace other special characters
#     text = text.replace('-', ' ')
#     text = re.sub('[\":\<>@\(\)]', '', text)

#     # insert white space before and after tokens:
#     for token in ['?', '.', ',', '!']:
#         text = insertSpace(token, text)

#     # insert white space for 's
#     text = insertSpace('\'s', text)

#     # replace it's, does't, you'd ... etc
#     text = re.sub('^\'', '', text)
#     text = re.sub('\'$', '', text)
#     text = re.sub('\'\s', ' ', text)
#     text = re.sub('\s\'', ' ', text)
#     for fromx, tox in replacements:
#         text = ' ' + text + ' '
#         text = text.replace(fromx, tox)[1:-1]

#     # remove multiple spaces
#     text = re.sub(' +', ' ', text)

#     # concatenate numbers
#     tmp = text
#     tokens = text.split()
#     i = 1
#     while i < len(tokens):
#         if re.match(u'^\d+$', tokens[i]) and \
#                 re.match(u'\d+$', tokens[i - 1]):
#             tokens[i - 1] += tokens[i]
#             del tokens[i]
#         else:
#             i += 1
#     text = ' '.join(tokens)

#     for time in times:
#       text = re.sub('\\[value_time\\]', time, text, 1)

#     for price in prices:
#       text = re.sub('\\[value_price\\]', price, text, 1)

#     return text

In [ ]:
# # filter
# import re
# import unicodedata
# import pandas

# def _is_punctuation(char):
#   """Checks whether `chars` is a punctuation character."""
#   cp = ord(char)
#   # We treat all non-letter/number ASCII as punctuation.
#   # Characters such as "^", "$", and "`" are not in the Unicode
#   # Punctuation class but we treat them as punctuation anyways, for
#   # consistency.
#   if ((cp >= 33 and cp <= 47) or (cp >= 58 and cp <= 64) or
#       (cp >= 91 and cp <= 96) or (cp >= 123 and cp <= 126)):
#     return True
#   cat = unicodedata.category(char)
#   if cat.startswith("P"):
#     return True
#   return False

# # A collection of phrases that are semantically similar to the key value, which
# # is a word.
# _SIMILAR_WORDS = {
#     'portuguese': ['portugese', 'portugeuese'],
#     '01:30': ['1 thirty p . m .'],
#     '16:30': ['after 16:00'],
#     'anatolia': ['anatoilia'],
#     'allenbell': ['allenball'],
#     'caribbean': ['carribbean'],
#     'seafood': ['sea food'],
#     'moroccan': ['morrocan'],
#     'avalon': ['avaion'],
#     'barbeque': ['bbq'],
#     'american': ['americas'],
#     'italian': ['pizza place'],
#     'indian': ['taj tandoori'],
#     'british': ['english'],
#     'cambride': ['cambridge'],
#     'fenditton': ['fen ditton'],
#     'cafe': ['caffe'],
#     'gonvile': ['gonville'],
#     'shaddia': ['shaddai'],
#     'center': ['centre']
# }

# import string
# labels = set()

# all_labels = {'restaurant-booktime': [], 'restaurant-area': [], 'restaurant-bookday': [], 'restaurant-pricerange': [], 'restaurant-name': [], 'restaurant-food': [], 'restaurant-bookpeople':[]}

# def filter(data):
#   global labels

#   result = []

#   for i, obj in enumerate(data):
#       turns = obj.get("turns", None)
#       for turn in turns:
#           if turn:
#               utterance = turn.get("utterance", None)
#               speaker = turn.get("speaker", None)
#               if utterance and speaker and speaker == "USER":
#                   frames = turn.get("frames", None)
#                   if frames:
#                       dic = dict()
#                       res = [[], []]
#                       gotValue = False
#                       for frame in frames: 
#                           state = frame.get("state", None)
#                           service = frame.get("service", None)
#                           if state : active_intent = state.get("active_intent", None)
#                           if service and service == "restaurant" and state and active_intent and active_intent != "NONE":
#                               slot_values = state.get("slot_values", None)
#                               if slot_values and len(slot_values) != 0:
#                                   gotValue = True
#                                   for key, value in slot_values.items():
#                                       for elem in value:
#                                         dic[elem] = key
#                                         itens_label = all_labels.get(key, None)
#                                         if itens_label is not None: itens_label.append(elem)


#                       if len(dic) > 0:
#                           phrase = utterance.lower()
#                           positions = []

#                           # keys2remove = []
#                           # for key, value in dic.items():
#                           #      labels.add(value)
#                           #      if key in phrase:
#                           #         res[0].append(key)
#                           #         res[1].append(value)

#                           #         keys2remove.append(key)

#                           #         for match in re.finditer(key, utterance):
#                           #            positions.append((match.start(), match.end()))
#                           #            break

#                           #         phrase = phrase.replace(key, "")                                  

#                           # for key2remove in keys2remove:
#                           #     dic.pop(key2remove)

#                           # normalizo a frase, mas n faco split
#                           normalizedPhrase = normalize(phrase)
#                           normalizedPhraseAux = normalizedPhrase
#                           keys2remove = []
#                           positions = []

#                           # pra cada slot value eu tento extrair ele da frase, ai achando eu pego a posicao 
#                           # na frase inicial e removo da frase auxiliar a palavra (composta)
#                           for key, value in dic.items():
#                                if key in normalizedPhraseAux:
#                                   # res[0].append(key)
#                                   # res[1].append(value)

#                                   keys2remove.append(key)

#                                   for match in re.finditer(re.escape(key), normalizedPhrase):
#                                     positions.append((key, value, match.start(), match.end()))
#                                     break

#                                   normalizedPhraseAux = normalizedPhraseAux.replace(key, "")

#                                   labels.add(value)

#                           # tiro do dicionario os slot values q ja peguei
#                           for key2remove in keys2remove:
#                               dic.pop(key2remove)

#                           #### pode botar outras tokenizações aq #####

#                           # só um sort pra poder pegar as frases de acordo com oq aparece na frase original
#                           sortedPositions = positions.copy()
#                           sortedPositions.sort(key=lambda elem : elem[2])

#                           # aq q eu realmente salvo no res
#                           # eu pego oq tiver antes do q peguei e boto como other (se n é um value é other)
#                           # eu dou um split pq ne
#                           lastEnd = 0
#                           for word, value, start, end in sortedPositions:
#                             if len(normalizedPhrase[lastEnd:start-1]) > 0:
#                               spplited = normalizedPhrase[lastEnd:start-1].split(" ")
#                               for s in spplited:
#                                 if s == "" : continue
                                
#                                 isPontuation = True
#                                 for letter in s.strip() : 
#                                   if not _is_punctuation(letter) : 
#                                     isPontuation = False
#                                     break
#                                 if isPontuation : continue

#                                 res[0].append(s)
#                                 res[1].append("O")
#                                 labels.add("O")
                            
#                             res[0].append(word)
#                             res[1].append(value)

#                             lastEnd = end


#                           # ai se faltou pegar algo no final da frase eu faço isso aq
#                           if lastEnd < len(normalizedPhrase):
#                             spplited = normalizedPhrase[lastEnd:len(normalizedPhrase)].split(" ")
#                             for s in spplited:
#                               if s == "" : continue

#                               res[0].append(s)
#                               res[1].append("O")
#                               labels.add("O")

#                           # leftoverPositions = []

#                           # for leftoverWord, startIndex, endIndex in [(m.group(0), (m.start(), m.end()-1)) for m in re.finditer(r'\S+', normalizedPhraseAux)]:
#                           #     length2add = 0
#                           #     for position in positions:
#                           #       if startIndex

#                           #     res[0].append(leftover)
#                           #     res[1].append("O")

#                           #     labels.add("O")


#                           # se a frase só tem other...
#                           onlyOther = True
#                           for token in res[1]:
#                               if token != "O" : 
#                                 onlyOther = False
#                                 break
                          
#                           if not onlyOther : result.append(res)
#                             # # caso tenha palavras repetidas
#                             # reptds = dict()
#                             # for i, word in enumerate(res[0]):
#                             #   nextIndex = i+1
#                             #   reptds[word] = []
#                             #   while word in res[nextIndex:] :
#                             #     nextIndex = res[nextIndex:].index(word)
#                             #     reptds[word].append(nextIndex)
#                             #     nextIndex += 1

#                             # posPhrase = []
#                             # countReptds = dict()
#                             # for wordDict in reptds:
#                             #   countReptds[word] = 0

#                             # for word in res[0]:
#                             #   for i, match in enumerate(re.finditer(re.escape(word), normalizedPhrase)):
#                             #     if reptds[word] :
#                             #       if countReptds[word] > i : continue
#                             #       else:
#                             #         posPhrase.append(match.start())
#                             #         countReptds[word] += 1
#                             #         break
#                             #     else : 
#                             #       posPhrase.append(match.start())
#                             #       break

#                             # # colocar em ordem
#                             # sorted = posPhrase.copy()
#                             # sorted.sort()

#                             # resAux = [[], []]
#                             # for index in sorted:
#                             #     i = posPhrase.index(index)
#                             #     resAux[0].append(res[0][i])
#                             #     resAux[1].append(res[1][i])

                            
#                             # result.append(resAux)



#                       # if gotValue:
#                       #     text = normalize(utterance)
                
#                       #     for word in text.split(" "):
#                       #         res[0].append(word)
#                       #         word_gotten = dic.get(word, "O")
#                       #         if word_gotten == "O":
#                       #             words2try = _SIMILAR_WORDS.get(word, None)
#                       #             if words2try:
#                       #               for _word in words2try:
#                       #                 word_gotten = dic.get(_word, "O")
#                       #                 if word_gotten != "O" : break

#                       #         if word_gotten == "O":
#                       #           for key, value in _SIMILAR_WORDS.items():
#                       #             for _word in value:
#                       #               if word == _word:
#                       #                 word_gotten = dic.get(key, "O")
#                       #                 if word_gotten == "O":
#                       #                   for __word in _SIMILAR_WORDS[key]:
#                       #                     word_gotten = dic.get(__word, "O")
#                       #                     if word_gotten != "O" : break
#                       #         res[1].append(word_gotten)
#                       #         labels.add(dic.get(word, "O"))
                          
#                           # onlyOther = True
#                           # for token in res[1]:
#                           #     if token != "O" : 
#                           #       onlyOther = False
#                           #       break
                          
#                           # if not onlyOther : result.append(res)




#   return result

# allTrains = [myJsonTrain2, myJsonTrain3, myJsonTrain4, myJsonTrain5, myJsonTrain6, myJsonTrain7, myJsonTrain8, myJsonTrain9, myJsonTrain10, myJsonTrain11, myJsonTrain12, myJsonTrain13, myJsonTrain14, myJsonTrain15, myJsonTrain16, myJsonTrain17]
# train_dataset = filter(myJsonTrain1)
# for train in allTrains:
#   train_dataset.extend(filter(train))
# p = {'restaurant-booktime': [], 'restaurant-area': [], 'restaurant-bookday': [], 'restaurant-pricerange': [], 'restaurant-name': [], 'restaurant-food': [], 'restaurant-bookpeople':[], "O": []}
# for elem in train_dataset:
#   for i, x in enumerate(elem[1]):
#     z = p.get(x, None)
#     if z is not None:
#       z.append(elem[0][i])
# print("for p:", p["restaurant-name"])
# for key,value in p.items():
#   print(key, " = ", len(value))

# print(len(train_dataset))
# print("for all labels:", all_labels["restaurant-name"])
# for key,value in all_labels.items():
#   print(key, " = ", len(value))
# # for i, elem in enumerate(train_dataset):
#       # print(elem)
#       # if i > 30:
#         # print("--------------------")
#         # break

# all_labels = {'restaurant-booktime': [], 'restaurant-area': [], 'restaurant-bookday': [], 'restaurant-pricerange': [], 'restaurant-name': [], 'restaurant-food': [], 'restaurant-bookpeople':[]}
# test_dataset = filter(myJsonTest1) + filter(myJsonTest2)
# print(len(test_dataset))
# for key,value in all_labels.items():
#   print(key, " = ", len(value))
# # for i, elem in enumerate(test_dataset):
#       # print(elem)
#       # if i > 30:
#         # print("--------------------")
#         # break

# (pandas.DataFrame(train_dataset)).to_csv("trains.csv")
# (pandas.DataFrame(test_dataset)).to_csv("tests.csv")
# (pandas.DataFrame(labels)).to_csv("labels.csv")
# print(labels)
# train_dataset[:5]

for p: ['don pasquale pizzeria', 'riverside brasserie', 'backstreet bistro', 'travellers rest', 'ask', 'bangkok city', 'ask', 'la mimosa', 'shiraz', 'pizza hut fen ditton', 'nados', 'the varsity restaurant', 'stazione restaurant and coffee bar', 'zizzi cambridge', 'gourmet burger kitchen', 'curry garden', 'maharajah tandoor restaurant', 'good', 'curry king', 'cotto', 'brasserie', 'royal spice', 'cocum', 'nandos', 'rice house', 'yippee noodle bar', 'fitzbillies restaurant', 'curry prince', 'yippee', 'de luca cucina and bar', 'the varsity restaurant', 'michael house cafe', 'ugly duckling', 'parkside pools', 'the oak bistro', 'cocum', 'bistro', 'nirala', 'prezzo', 'jinling noodle bar', 'kymmoy', 'bangkok city', 'pizza express', 'caffe uno', 'travellers rest', 'nandos', 'nandos', 'city stop restaurant', 'la mimosa', 'ugly duckling', 'maharajah tandoori restaurant', 'good luck', 'thanh binh', 'mahal of cambridge', 'tandoori palace', 'shiraz', 'rajmahal', 'alimentum', 'the gardenia', 'zizzi 

[[['i',
   'need',
   'a',
   'place',
   'to',
   'dine',
   'in',
   'the',
   'center',
   'thats',
   'expensive'],
  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'restaurant-pricerange']],
 [['any',
   'sort',
   'of',
   'food',
   'would',
   'be',
   'fine',
   'as',
   'long',
   'as',
   'it',
   'is',
   'a',
   'bit',
   'expensive',
   '.',
   'could',
   'i',
   'get',
   'the',
   'phone',
   'number',
   'for',
   'your',
   'recommendation',
   '?'],
  ['O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'restaurant-pricerange',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O']],
 [['sounds',
   'good',
   'could',
   'i',
   'get',
   'that',
   'phone',
   'number',
   'also',
   'could',
   'you',
   'recommend',
   'me',
   'an',
   'expensive',
   'hotel',
   '?'],
  ['O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
  

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas
import ast

pathTrain = "/content/drive/MyDrive/PLN/Projeto/trains.csv"
pathTest = "/content/drive/MyDrive/PLN/Projeto/tests.csv"
pathLabels = "/content/drive/MyDrive/PLN/Projeto/labels.csv";

train_dataset = pandas.read_csv(pathTrain, index_col=0).applymap(ast.literal_eval).values.tolist()
test_dataset = pandas.read_csv(pathTest, index_col=0).applymap(ast.literal_eval).values.tolist()
labels = set(pandas.read_csv(pathLabels, index_col=0).values.flatten())

print(train_dataset[0:5])
print("Labels:", labels)

[[['i', 'need', 'a', 'place', 'to', 'dine', 'in', 'the', 'center', 'thats', 'expensive'], ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'restaurant-pricerange']], [['any', 'sort', 'of', 'food', 'would', 'be', 'fine', 'as', 'long', 'as', 'it', 'is', 'a', 'bit', 'expensive', '.', 'could', 'i', 'get', 'the', 'phone', 'number', 'for', 'your', 'recommendation', '?'], ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'restaurant-pricerange', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']], [['sounds', 'good', 'could', 'i', 'get', 'that', 'phone', 'number', 'also', 'could', 'you', 'recommend', 'me', 'an', 'expensive', 'hotel', '?'], ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'restaurant-pricerange', 'O', 'O']], [['yeah', 'i', 'need', 'a', 'restaurant', 'in', 'the', 'west', 'and', 'with', 'expensive', 'pricing', '.'], ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'restaurant-area', 'O', 'O', 'restaurant-pricerange', 'O', 'O']], [['it', 's', '

In [ ]:
# for i, label in enumerate(train_dataset[1]):
#     if 'other' in label:
#       train_dataset[1][i] = 'O'

# for i, label in enumerate(test_dataset[1]):
#     if 'other' in label:
#       test_dataset[1][i] = 'O'
      
# if 'other' in labels: labels.remove('other')
# labels.add('O')
# print(labels)

# create character vocab
all_text = " ".join([" ".join(x[0]) for x in train_dataset+test_dataset])
vocab = sorted(set(all_text))

# create character/id and label/id mapping
char2idx = {u:i+1 for i, u in enumerate(vocab)}
idx2char = np.array(vocab)
label2idx = {u:i+1 for i, u in enumerate(labels)}
idx2label = np.array(labels)

print(idx2label)
print(char2idx)

{'restaurant-pricerange', 'restaurant-name', 'restaurant-booktime', 'restaurant-bookpeople', 'restaurant-bookday', 'O', 'restaurant-area', 'restaurant-food'}
{' ': 1, '!': 2, '#': 3, '%': 4, '&': 5, "'": 6, '*': 7, ',': 8, '-': 9, '.': 10, '0': 11, '1': 12, '2': 13, '3': 14, '4': 15, '5': 16, '6': 17, '7': 18, '8': 19, '9': 20, ':': 21, '?': 22, '`': 23, 'a': 24, 'b': 25, 'c': 26, 'd': 27, 'e': 28, 'f': 29, 'g': 30, 'h': 31, 'i': 32, 'j': 33, 'k': 34, 'l': 35, 'm': 36, 'n': 37, 'o': 38, 'p': 39, 'q': 40, 'r': 41, 's': 42, 't': 43, 'u': 44, 'v': 45, 'w': 46, 'x': 47, 'y': 48, 'z': 49}


In [ ]:
def split_char_labels(eg):
  '''
  For a given input/output example, break tokens into characters while keeping 
  the same label.
  '''

  tokens = eg[0]
  labels = eg[1]

  input_chars = []
  output_char_labels = []

  for token,label in zip(tokens,labels):
    input_chars.extend([char for char in token])
    input_chars.extend(' ')
    output_char_labels.extend([label]*len(token))
    output_char_labels.extend('O')

  return [[char2idx[x] for x in input_chars[:-1]], np.array([label2idx[x] for x in output_char_labels[:-1]])]


train_formatted = [split_char_labels(eg) for eg in train_dataset]
test_formatted = [split_char_labels(eg) for eg in test_dataset]

print(len(train_formatted))
print(len(test_formatted))

10193
1263


In [ ]:
# training generator
def gen_train_series():

    for eg in train_formatted:
      yield eg[0],eg[1]

# validation generator
def gen_valid_series():

    for eg in valid_formatted:
      yield eg[0],eg[1]

# test generator
def gen_test_series():

  for eg in test_formatted:
      yield eg[0],eg[1]
  
# create Dataset objects for train, test and validation sets  
series = tf.data.Dataset.from_generator(gen_train_series,output_types=(tf.int32, tf.int32),output_shapes = ((None, None)))
series_test = tf.data.Dataset.from_generator(gen_test_series,output_types=(tf.int32, tf.int32),output_shapes = ((None, None)))

BATCH_SIZE = 128
BUFFER_SIZE=1000

# create padded batch series objects for train, test and validation sets
ds_series_batch = series.shuffle(BUFFER_SIZE).padded_batch(BATCH_SIZE, padded_shapes=([None], [None]), drop_remainder=True)
ds_series_batch_test = series_test.padded_batch(BATCH_SIZE, padded_shapes=([None], [None]), drop_remainder=True)

# print example batches
for input_example_batch, target_example_batch in ds_series_batch_test.take(1):
  print(input_example_batch)
  print(target_example_batch)

tf.Tensor(
[[31 28 35 ...  0  0  0]
 [26 24 37 ...  0  0  0]
 [24 26 43 ...  0  0  0]
 ...
 [32  1 46 ...  0  0  0]
 [26 24 37 ...  0  0  0]
 [43 41 48 ...  0  0  0]], shape=(128, 167), dtype=int32)
tf.Tensor(
[[6 6 6 ... 0 0 0]
 [6 6 6 ... 0 0 0]
 [6 6 6 ... 0 0 0]
 ...
 [6 6 6 ... 0 0 0]
 [6 6 6 ... 0 0 0]
 [6 6 6 ... 0 0 0]], shape=(128, 167), dtype=int32)


In [ ]:
vocab_size = len(vocab)+1

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 256

label_size = len(labels)  

# build LSTM model
def build_model(vocab_size,label_size, embedding_dim, rnn_units, batch_size):
      model = tf.keras.Sequential([
          tf.keras.layers.Embedding(vocab_size, embedding_dim,
                                    batch_input_shape=[batch_size, None],mask_zero=True),
          tf.keras.layers.LSTM(rnn_units,
                               return_sequences=True,
                               stateful=True,
                               recurrent_initializer='glorot_uniform'),
          tf.keras.layers.Dense(label_size)
          ])
      return model

model = build_model(
        vocab_size=len(vocab)+1,
        label_size=len(labels)+1,
        embedding_dim=embedding_dim,
        rnn_units=rnn_units,
        batch_size=BATCH_SIZE)

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (128, None, 256)          12800     
_________________________________________________________________
lstm_3 (LSTM)                (128, None, 256)          525312    
_________________________________________________________________
dense_3 (Dense)              (128, None, 9)            2313      
Total params: 540,425
Trainable params: 540,425
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import os
!pip install tensorflow-addons
import tensorflow_addons as tfa
import keras.backend as K
from sklearn.metrics import f1_score

# def f1_metric(y_true, y_pred):
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
#     possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
#     predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
#     precision = true_positives / (predicted_positives + K.epsilon())
#     recall = true_positives / (possible_positives + K.epsilon())
#     f1_val = 2*(precision*recall)/(precision+recall+K.epsilon())
#     return f1_val


# define loss function
def loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

# def f1Score(labels, logits):
#   print(labels.numpy().shape, logits.numpy().shape)
#   return f1_score(labels.numpy(), logits.numpy())

# def recall(y_true, y_pred):
#     y_true = K.ones_like(y_true) 
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
#     all_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    
#     recall = true_positives / (all_positives + K.epsilon())
#     return recall

# def precision(y_true, y_pred):
#     y_true = K.ones_like(y_true) 
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    
#     predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
#     precision = true_positives / (predicted_positives + K.epsilon())
#     return precision

# def f1_score(y_true, y_pred):
#     precision_m = precision(y_true, y_pred)
#     recall_m = recall(y_true, y_pred)
#     return 2*((precision_m*recall_m)/(precision_m+recall_m+K.epsilon()))

# model.compile(optimizer='adam', loss=loss,metrics=[tf.keras.metrics.SparseCategoricalAccuracy(), f1_metric])
model.compile(optimizer='adam', loss=loss,metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [ ]:
EPOCHS=50 # aparentemente melhor valor é 45, pq os valores não melhoram significativamente e o collab fica bem mais lento depois
history = model.fit(ds_series_batch, epochs=EPOCHS, validation_data=ds_series_batch_test,callbacks=[checkpoint_callback])
# pra o keras pegar o melhor: checkpoint_callback

Epoch 1/50
79/79 [==============================] - 176s 2s/step - loss: 0.1816 - sparse_categorical_accuracy: 0.8701 - val_loss: 0.1481 - val_sparse_categorical_accuracy: 0.8895
Epoch 2/50
79/79 [==============================] - 171s 2s/step - loss: 0.1281 - sparse_categorical_accuracy: 0.9025 - val_loss: 0.1106 - val_sparse_categorical_accuracy: 0.9133
Epoch 3/50
79/79 [==============================] - 176s 2s/step - loss: 0.0950 - sparse_categorical_accuracy: 0.9238 - val_loss: 0.0892 - val_sparse_categorical_accuracy: 0.9288
Epoch 4/50
79/79 [==============================] - 172s 2s/step - loss: 0.0794 - sparse_categorical_accuracy: 0.9368 - val_loss: 0.0761 - val_sparse_categorical_accuracy: 0.9388
Epoch 5/50
79/79 [==============================] - 174s 2s/step - loss: 0.0684 - sparse_categorical_accuracy: 0.9450 - val_loss: 0.0649 - val_sparse_categorical_accuracy: 0.9467
Epoch 6/50
79/79 [==============================] - 172s 2s/step - loss: 0.0604 - sparse_categorical_accu

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

preds = np.array([])
y_trues= np.array([])

# iterate through test set, make predictions based on trained model
for input_example_batch, target_example_batch in ds_series_batch_test:

  pred=model.predict_on_batch(input_example_batch)
  pred_max=tf.argmax(tf.nn.softmax(pred),2).numpy().flatten()
  y_true=target_example_batch.numpy().flatten()

  preds=np.concatenate([preds,pred_max])
  y_trues=np.concatenate([y_trues,y_true])

# remove padding from evaluation
remove_padding = [(p,y) for p,y in zip(preds,y_trues) if y!=0]

r_p = [x[0] for x in remove_padding]
r_t = [x[1] for x in remove_padding]

# print confusion matrix and classification report
print(confusion_matrix(r_p,r_t))
print(classification_report(r_p,r_t, zero_division=0))

[[ 2263    14     1     0     1   106    11    60]
 [    7  1817     0     0     3   247     6    12]
 [    0     0   980     8     0   224     0     0]
 [    0     0    19   278     0    29     0     0]
 [    3     2     0     0  1892    95     0     2]
 [   35   425   165    15   172 68384    51   231]
 [   16    14     0     0     5   160  1441     1]
 [   25    19     2     0     3   209     0  2760]]
              precision    recall  f1-score   support

         1.0       0.96      0.92      0.94      2456
         2.0       0.79      0.87      0.83      2092
         3.0       0.84      0.81      0.82      1212
         4.0       0.92      0.85      0.89       326
         5.0       0.91      0.95      0.93      1994
         6.0       0.98      0.98      0.98     69478
         7.0       0.95      0.88      0.92      1637
         8.0       0.90      0.91      0.91      3018

    accuracy                           0.97     82213
   macro avg       0.91      0.90      0.90     8

In [ ]:
# coding=utf-8
# Copyright 2021 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tokenization classes. Copied from bert."""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import collections
import re
import unicodedata

from absl import flags
import six
import tensorflow.compat.v1 as tf

# FLAGS = flags.FLAGS

# flags.DEFINE_bool(
#     "preserve_unused_tokens", False,
#     "If True, Wordpiece tokenization will not be applied to words in the vocab."
# )

preserve_unused_tokens = False

_UNUSED_TOKEN_RE = re.compile("^\\[unused\\d+\\]$")


def preserve_token(token, vocab):
  """Returns True if the token should forgo tokenization and be preserved."""
  # if not FLAGS.preserve_unused_tokens:
  if not preserve_unused_tokens:
    return False
  if token not in vocab:
    return False
  return bool(_UNUSED_TOKEN_RE.search(token))


def validate_case_matches_checkpoint(do_lower_case, init_checkpoint):
  """Checks whether the casing config is consistent with the checkpoint name."""

  # The casing has to be passed in by the user and there is no explicit check
  # as to whether it matches the checkpoint. The casing information probably
  # should have been stored in the bert_config.json file, but it's not, so
  # we have to heuristically detect it to validate.

  if not init_checkpoint:
    return

  m = re.match("^.*?([A-Za-z0-9_-]+)/bert_model.ckpt", init_checkpoint)
  if m is None:
    return

  model_name = m.group(1)

  lower_models = [
      "uncased_L-24_H-1024_A-16", "uncased_L-12_H-768_A-12",
      "multilingual_L-12_H-768_A-12", "chinese_L-12_H-768_A-12"
  ]

  cased_models = [
      "cased_L-12_H-768_A-12", "cased_L-24_H-1024_A-16",
      "multi_cased_L-12_H-768_A-12"
  ]

  is_bad_config = False
  if model_name in lower_models and not do_lower_case:
    is_bad_config = True
    actual_flag = "False"
    case_name = "lowercased"
    opposite_flag = "True"

  if model_name in cased_models and do_lower_case:
    is_bad_config = True
    actual_flag = "True"
    case_name = "cased"
    opposite_flag = "False"

  if is_bad_config:
    raise ValueError(
        "You passed in `--do_lower_case=%s` with `--init_checkpoint=%s`. "
        "However, `%s` seems to be a %s model, so you "
        "should pass in `--do_lower_case=%s` so that the fine-tuning matches "
        "how the model was pre-training. If this error is wrong, please "
        "just comment out this check." % (actual_flag, init_checkpoint,
                                          model_name, case_name, opposite_flag))


def convert_to_unicode(text):
  """Converts `text` to Unicode (if it's not already), assuming utf-8 input."""
  if six.PY3:
    if isinstance(text, str):
      return text
    elif isinstance(text, bytes):
      return text.decode("utf-8", "ignore")
    else:
      raise ValueError("Unsupported string type: %s" % (type(text)))
  elif six.PY2:
    if isinstance(text, str):
      return text.decode("utf-8", "ignore")
    elif isinstance(text, unicode):
      return text
    else:
      raise ValueError("Unsupported string type: %s" % (type(text)))
  else:
    raise ValueError("Not running on Python2 or Python 3?")


def printable_text(text):
  """Returns text encoded in a way suitable for print or `tf.logging`."""

  # These functions want `str` for both Python2 and Python3, but in one case
  # it's a Unicode string and in the other it's a byte string.
  if six.PY3:
    if isinstance(text, str):
      return text
    elif isinstance(text, bytes):
      return text.decode("utf-8", "ignore")
    else:
      raise ValueError("Unsupported string type: %s" % (type(text)))
  elif six.PY2:
    if isinstance(text, str):
      return text
    elif isinstance(text, unicode):
      return text.encode("utf-8")
    else:
      raise ValueError("Unsupported string type: %s" % (type(text)))
  else:
    raise ValueError("Not running on Python2 or Python 3?")


def load_vocab(vocab_file):
  """Loads a vocabulary file into a dictionary."""
  vocab = collections.OrderedDict()
  with tf.io.gfile.GFile(vocab_file, "r") as reader:
    while True:
      token = convert_to_unicode(reader.readline())
      if not token:
        break
      token = token.strip()
      if token not in vocab:
        vocab[token] = len(vocab)
  return vocab


def convert_by_vocab(vocab, items):
  """Converts a sequence of [tokens|ids] using the vocab."""
  output = []
  for item in items:
    output.append(vocab[item])
  return output


def convert_tokens_to_ids(vocab, tokens):
  return convert_by_vocab(vocab, tokens)


def convert_ids_to_tokens(inv_vocab, ids):
  return convert_by_vocab(inv_vocab, ids)


def whitespace_tokenize(text):
  """Runs basic whitespace cleaning and splitting on a piece of text."""
  text = text.strip()
  if not text:
    return []
  tokens = text.split()
  return tokens


class FullTokenizer(object):
  """Runs end-to-end tokenziation."""

  def __init__(self, vocab_file, do_lower_case=True):
    self.vocab = load_vocab(vocab_file)
    self.inv_vocab = {v: k for k, v in self.vocab.items()}
    self.basic_tokenizer = BasicTokenizer(
        do_lower_case=do_lower_case, vocab=self.vocab)
    self.wordpiece_tokenizer = WordpieceTokenizer(vocab=self.vocab)

  def tokenize(self, text):
    split_tokens = []
    for token in self.basic_tokenizer.tokenize(text):
      if preserve_token(token, self.vocab):
        split_tokens.append(token)
        continue
      for sub_token in self.wordpiece_tokenizer.tokenize(token):
        split_tokens.append(sub_token)

    return split_tokens

  def convert_tokens_to_ids(self, tokens):
    return convert_by_vocab(self.vocab, tokens)

  def convert_ids_to_tokens(self, ids):
    return convert_by_vocab(self.inv_vocab, ids)


class BasicTokenizer(object):
  """Runs basic tokenization (punctuation splitting, lower casing, etc.)."""

  def __init__(self, do_lower_case=True, vocab=tuple()):
    """Constructs a BasicTokenizer.

    Args:
      do_lower_case: Whether to lower case the input.
      vocab: A container of tokens to not mutate during tokenization.
    """
    self.do_lower_case = do_lower_case
    self.vocab = vocab

  def tokenize(self, text):
    """Tokenizes a piece of text."""
    text = convert_to_unicode(text)
    text = self._clean_text(text)

    # This was added on November 1st, 2018 for the multilingual and Chinese
    # models. This is also applied to the English models now, but it doesn't
    # matter since the English models were not trained on any Chinese data
    # and generally don't have any Chinese data in them (there are Chinese
    # characters in the vocabulary because Wikipedia does have some Chinese
    # words in the English Wikipedia.).
    text = self._tokenize_chinese_chars(text)

    orig_tokens = whitespace_tokenize(text)
    split_tokens = []
    for token in orig_tokens:
      if preserve_token(token, self.vocab):
        split_tokens.append(token)
        continue
      if self.do_lower_case:
        token = token.lower()
        token = self._run_strip_accents(token)
      split_tokens.extend(self._run_split_on_punc(token))

    output_tokens = whitespace_tokenize(" ".join(split_tokens))
    return output_tokens

  def _run_strip_accents(self, text):
    """Strips accents from a piece of text."""
    text = unicodedata.normalize("NFD", text)
    output = []
    for char in text:
      cat = unicodedata.category(char)
      if cat == "Mn":
        continue
      output.append(char)
    return "".join(output)

  def _run_split_on_punc(self, text):
    """Splits punctuation on a piece of text."""
    chars = list(text)
    i = 0
    start_new_word = True
    output = []
    while i < len(chars):
      char = chars[i]
      if _is_punctuation(char):
        output.append([char])
        start_new_word = True
      else:
        if start_new_word:
          output.append([])
        start_new_word = False
        output[-1].append(char)
      i += 1

    return ["".join(x) for x in output]

  def _tokenize_chinese_chars(self, text):
    """Adds whitespace around any CJK character."""
    output = []
    for char in text:
      cp = ord(char)
      if self._is_chinese_char(cp):
        output.append(" ")
        output.append(char)
        output.append(" ")
      else:
        output.append(char)
    return "".join(output)

  def _is_chinese_char(self, cp):
    """Checks whether CP is the codepoint of a CJK character."""
    # This defines a "chinese character" as anything in the CJK Unicode block:
    #   https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_(Unicode_block)
    #
    # Note that the CJK Unicode block is NOT all Japanese and Korean characters,
    # despite its name. The modern Korean Hangul alphabet is a different block,
    # as is Japanese Hiragana and Katakana. Those alphabets are used to write
    # space-separated words, so they are not treated specially and handled
    # like the all of the other languages.
    if ((cp >= 0x4E00 and cp <= 0x9FFF) or  #
        (cp >= 0x3400 and cp <= 0x4DBF) or  #
        (cp >= 0x20000 and cp <= 0x2A6DF) or  #
        (cp >= 0x2A700 and cp <= 0x2B73F) or  #
        (cp >= 0x2B740 and cp <= 0x2B81F) or  #
        (cp >= 0x2B820 and cp <= 0x2CEAF) or
        (cp >= 0xF900 and cp <= 0xFAFF) or  #
        (cp >= 0x2F800 and cp <= 0x2FA1F)):  #
      return True

    return False

  def _clean_text(self, text):
    """Performs invalid character removal and whitespace cleanup on text."""
    output = []
    for char in text:
      cp = ord(char)
      if cp == 0 or cp == 0xfffd or _is_control(char):
        continue
      if _is_whitespace(char):
        output.append(" ")
      else:
        output.append(char)
    return "".join(output)


class WordpieceTokenizer(object):
  """Runs WordPiece tokenziation."""

  def __init__(self, vocab, unk_token="[UNK]", max_input_chars_per_word=200):
    self.vocab = vocab
    self.unk_token = unk_token
    self.max_input_chars_per_word = max_input_chars_per_word

  def tokenize(self, text):
    """Tokenizes a piece of text into its word pieces.

    This uses a greedy longest-match-first algorithm to perform tokenization
    using the given vocabulary.

    For example:
      input = "unaffable"
      output = ["un", "##aff", "##able"]

    Args:
      text: A single token or whitespace separated tokens. This should have
        already been passed through `BasicTokenizer.

    Returns:
      A list of wordpiece tokens.
    """

    text = convert_to_unicode(text)

    output_tokens = []
    for token in whitespace_tokenize(text):
      chars = list(token)
      if len(chars) > self.max_input_chars_per_word:
        output_tokens.append(self.unk_token)
        continue

      is_bad = False
      start = 0
      sub_tokens = []
      while start < len(chars):
        end = len(chars)
        cur_substr = None
        while start < end:
          substr = "".join(chars[start:end])
          if start > 0:
            substr = "##" + substr
          if substr in self.vocab:
            cur_substr = substr
            break
          end -= 1
        if cur_substr is None:
          is_bad = True
          break
        sub_tokens.append(cur_substr)
        start = end

      if is_bad:
        output_tokens.append(self.unk_token)
      else:
        output_tokens.extend(sub_tokens)
    return output_tokens


def _is_whitespace(char):
  """Checks whether `chars` is a whitespace character."""
  # \t, \n, and \r are technically control characters but we treat them
  # as whitespace since they are generally considered as such.
  if char == " " or char == "\t" or char == "\n" or char == "\r":
    return True
  cat = unicodedata.category(char)
  if cat == "Zs":
    return True
  return False


def _is_control(char):
  """Checks whether `chars` is a control character."""
  # These are technically control characters but we count them as whitespace
  # characters.
  if char == "\t" or char == "\n" or char == "\r":
    return False
  cat = unicodedata.category(char)
  if cat in ("Cc", "Cf"):
    return True
  return False

def _is_punctuation(char):
  """Checks whether `chars` is a punctuation character."""
  cp = ord(char)
  # We treat all non-letter/number ASCII as punctuation.
  # Characters such as "^", "$", and "`" are not in the Unicode
  # Punctuation class but we treat them as punctuation anyways, for
  # consistency.
  if ((cp >= 33 and cp <= 47) or (cp >= 58 and cp <= 64) or
      (cp >= 91 and cp <= 96) or (cp >= 123 and cp <= 126)):
    return True
  cat = unicodedata.category(char)
  if cat.startswith("P"):
    return True
  return False

In [ ]:
_DEFAULT_SERVICE_NAME = 'all'
# "Don't care" slot value.
_DONT_CARE = 'dontcare'
_NONE_VALUE = 'none'
_INACTIVE_INTENT = 'NONE'
# Maximum number of dialogues to write in each output file.
_NUM_DIALS_PER_FILE = 512

# We try to find the span of non-categorical slot values in the dialog history,
# but sometimes there is no exact match and we choose to find the closest values
# from the utterance. If the found value is contained in the list below,
# we need to check if it is a correct match.
_FOUND_VALUES_NEED_CHECK = [
    'restaurant', 'hotel', 'museum', 'church', 'college', 'cinema', 'park',
    'guesthouses', 'guesthouse', 'great', 'from', 'hotels', 'school', 'schools',
    'guests', 'colleges', 'lodge', 'theatre', 'centre', 'bar',
    'bed and breakfast', 'train', 'station', 'gallery', 'la', 'time', 'house',
    'guest house', 'old', 'pool', 'house', 'a', 'b', 'the', 'cafe', 'cambridge',
    'hospital', 'restaurant\'s'
]

# A collection of phrases that are semantically similar to the key value, which
# is a word.
_SIMILAR_WORDS = {
    'portuguese': ['portugese', 'portugeuese'],
    '01:30': ['1 thirty p . m .'],
    '16:30': ['after 16:00'],
    'anatolia': ['anatoilia'],
    'allenbell': ['allenball'],
    'caribbean': ['carribbean'],
    'seafood': ['sea food'],
    'moroccan': ['morrocan'],
    'avalon': ['avaion'],
    'barbeque': ['bbq'],
    'american': ['americas'],
    'italian': ['pizza place'],
    'indian': ['taj tandoori'],
    'british': ['english'],
    'cambride': ['cambridge'],
    'fenditton': ['fen ditton'],
    'cafe': ['caffe'],
    'gonvile': ['gonville'],
    'shaddia': ['shaddai']
}

# A collection of phrases that are semantically similar to the key value, which
# is a phrase consisted of more than one word.
_SIMILAR_PHRASES = {
    'alexander bed and breakfast': [
        'alexander b&b', 'alexander bed and breafast',
        'alexander bed & breakfast'
    ],
    'a and b guest house': [
        'a & b guest house', 'a and b guesthouse', 'a and be guest house'
    ],
    'saint johns chop house': ['saint johns chop shop house'],
    'bridge guest house': ['bridge guesthouse'],
    'finches b and b': ['finches b & b', 'finches b&b'],
    'finches bed and breakfast': ['flinches bed and breakfast', 'finches b&b'],
    'carolina bed and breakfast': ['carolina b&b'],
    'city centre north b and b': [
        'city centre north b&b', 'city centre north b & b'
    ],
    'lan hong house': ['ian hong house', 'ian hong'],
    'ugly duckling': ['ugly ducking'],
    'sri lankan': ['sri lanken'],
    'cambridge punter': ['cambridge punte'],
    'abc theatre': ['adc theatre']
}

def _locate_boundary(phrase, text):
  """Locate the span of the phrase using exact match."""

  def _locate_token_boundary(pos, text):
    """Get the start and end index of a token that covers a certain position."""
    if pos < 0:
      raise ValueError('Pos {} should be a positive integer.'.format(pos))
    next_space = text.find(' ', pos)
    left_boundary = text.rfind(' ', 0, pos) + 1
    right_boundary = next_space if next_space != -1 else len(text)
    return left_boundary, right_boundary

  phrase = phrase.strip()
  pos_in_text = text.find(phrase)
  if pos_in_text == -1:
    return None, None

  tokens = phrase.split()
  start_idx, _ = _locate_token_boundary(pos_in_text, text)
  last_token = tokens[-1]
  find_last_token = text.find(last_token,
                              pos_in_text + len(phrase) - len(last_token))
  if find_last_token == -1:
    raise ValueError('Should find the last word for value {}'.format(phrase))
  _, end_idx = _locate_token_boundary(find_last_token, text)
  # If it's a number, the value should be exactly the same.
  if phrase.isdigit() and text[start_idx:end_idx] != phrase:
    return None, None
  # If the phrase is short, the value should be exactly the same.
  # e.g. we don't want to match "theatre" when searching for "the"
  if (len(phrase) <= 3 and len(phrase) != (end_idx - start_idx)):
    return None, None
  return start_idx, end_idx

def _locate_word(word, text, start_pos):
  """Get start and end index of a phrase that semantically equals to a word."""
  # If the word to search for contains 3 or 4 digits, correct it into time.
  obj = re.match(r'(?<!\d)\d{3,4}(?!\d)', word)

  assert start_pos <= len(text)
  if start_pos == len(text):
    return None, None
  text = text[start_pos:]
  if obj:
    if int(obj.group()) < 10000:
      word = ':'.join([obj.group(0)[:-2], obj.group(0)[-2:]])
  obj = re.match(r'^(\d+):(\d+)', word)
  if obj:
    # If word is about time, try different variations.
    # e.g. 10:15 can be written as 1015 or 10.15.
    times_to_try = [
        obj.group(0),
        obj.group(1) + obj.group(2), '.'.join([obj.group(1),
                                               obj.group(2)])
    ]
    hour = int(obj.group(1))
    minute = int(obj.group(2))
    if hour > 12:
      times_to_try.append(':'.join([str(hour - 12), obj.group(2)]))
      if minute == 0:
        times_to_try.append(str(hour - 12) + ' pm')
        times_to_try.append(str(hour - 12) + 'pm')
        times_to_try.append(str(hour - 12) + ' p . m .')
        times_to_try.append(str(hour - 12) + ' o\'clock p . m .')
        times_to_try.append(str(hour - 12) + ' o\'clock')
        times_to_try.append(str(hour) + ' o\'clock')
        times_to_try.append(str(hour - 12) + ':00')
        times_to_try.append(str(hour))
    elif (hour == 12 and minute == 0):
      times_to_try.extend(
          ['12 pm', '12pm', '12 o\'clock', '12 p . m .', '12', 'noon'])
    else:
      times_to_try.append(':'.join([str(hour + 12), obj.group(2)]))
      if int(minute) == 0:
        times_to_try.append(str(hour) + ' am')
        times_to_try.append(str(hour) + 'am')
        times_to_try.append(str(hour) + ' a . m .')
        times_to_try.append(str(hour) + ' o\'clock a . m .')
        times_to_try.append(str(hour) + ' o\'clock')
        times_to_try.append(str(hour + 12) + ':00')
        times_to_try.append(str(hour))
    if (minute == 15 or minute == 45 or minute == 30):
      times_to_try.append('after ' + str(hour) + ':' + str(minute - 15))
      if hour < 10:
        times_to_try.append('after 0' + str(hour) + ':' + str(minute - 15))
    if minute == 0:
      times_to_try.append('after ' + str(hour - 1) + ':45')
    for time_value in times_to_try:
      # Correct time like "08:15" to "8:15" to increase match possibility.
      if time_value[0] == '0':
        if len(time_value) > 2 and time_value[1] != [':']:
          time_value = time_value[1:]
      start_idx, end_idx = _locate_boundary(time_value, text)
  else:
    start_idx, end_idx = _locate_boundary(word, text)
    if start_idx is not None:
      return start_idx + start_pos, end_idx + start_pos
  # Try phrases that is similar to the word to find.
  for similar_word in _SIMILAR_WORDS.get(word, []):
    start_idx, end_idx = _locate_boundary(similar_word, text)
    if start_idx is not None:
      return start_idx + start_pos, end_idx + start_pos

  # Slot values ended with 's' can be written in different formats.
  # e.g. rosas can be written as rosa, rosa's.
  if word.endswith('s') and len(word) > 3:
    modified_words = [word[:-1] + '\'s', word[:-1]]
    for modified_word in modified_words:
      start_idx, end_idx = _locate_boundary(modified_word, text)
      if start_idx is not None:
        return start_idx + start_pos, end_idx + start_pos
  return None, None

In [ ]:
# Tokenize the slot value and find each of them.
                          # splitted_text = utterance.strip().split()
                          # found_tokens = []
                          # search_start_idx = 0
                          # # Find if each token exists in the utterance.
                          # for i, value_tok in enumerate(splitted_text):
                          #   tok_start_idx, tok_end_idx = _locate_word(value_tok, utterance, search_start_idx)
                          #   if tok_start_idx is not None and tok_end_idx is not None:
                          #     # Hard coded rules
                          #     # if the value to find is one of ['and', 'of', 'by'] and
                          #     # there's no token prior to them having been found, we don't think
                          #     # the value as found since they are fairly common words.
                          #     if value_tok not in ['and', 'of', 'by']:
                          #       to_get = utterance[tok_start_idx:tok_end_idx]
                          #       getting = ""
                          #       for _char in to_get:
                          #         if not _is_punctuation(_char):
                          #           getting += _char
                          #       found_tokens.append(getting)
                          
                          #     search_start_idx = tok_end_idx


                          # tokenizer = BasicTokenizer()
                          # text = tokenizer.tokenize(utterance)
                          # text = tokenizer.tokenize(utterance)
                        